Project/Backend_.NetCore_3_1/StefaniniCore.UI/Controllers/ProfileTypesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StefaniniCore.Application.AppInterfaces;
using StefaniniCore.Application.InputModels.ProfileTypes;
using System;

namespace StefaniniCore.UI.Controllers
{
    public class ProfileTypesController : MainController
    {
        private readonly IProfileTypeAppService _appService;
        private readonly ILogger<UserSystemsController> _logger;

        public ProfileTypesController(IProfileTypeAppService appService, ILogger<UserSystemsController> logger)
        {
            _appService = appService;
            _logger = logger;
        }

        [Authorize]
        public IActionResult Detail(int? profileTypeId)
        {
            try
            {
                if ((profileTypeId != null) && (profileTypeId > 0))
                    return View(_appService.GetById((int)profileTypeId));
                else
                    return View(_appService.GetListsPopulated());
            }
            catch (Exception ex)
            {
                return ErrorMessage(_logger, ex);
            }
        }

        [Authorize]
        public IActionResult List()
        {
            try
            {
                var viewModel = _appService.GetAll();
                return View(viewModel);
            }
            catch (Exception ex)
            {
                return ErrorMessage(_logger, ex);
            }
        }

        [Authorize]
        [HttpPost]
        public IActionResult Save(ProfileTypeInputModel inputModel)
        {
            try
            {
                var profileType = _appService.Save(inputModel);
                return SuccessMessage("Salvo com sucesso!", profileType.Id, false);
            }
            catch (Exception ex)
            {
                return ErrorMessage(_logger, ex);
            }
        }

        [Authorize]
        [HttpDelete]
        public IActionResult Remove(int profileTypeId)
        {
            try
            {
                _appService.DeleteById(profileTypeId);
                return SuccessMessage("Excluído com sucesso!", null, true);
            }
            catch (Exception ex)
            {
                return ErrorMessage(_logger, ex);
            }
        }
    }
}

Project/Backend_.NetCore_3_1/StefaniniCore.UI/Controllers/TasksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StefaniniCore.Application.AppInterfaces;
using StefaniniCore.Application.InputModels.Tasks;
using StefaniniCore.Application.ViewModels;
using System;

namespace StefaniniCore.UI.Controllers
{
    public class TasksController : MainController
    {
        private readonly ILogger<TasksController> _logger;
        private readonly ITaskAppService _appService;

        public TasksController(ILogger<TasksController> logger, ITaskAppService appService)
        {
            _logger = logger;
            _appService = appService;
        }

        [Authorize]
        public IActionResult List()
        {
            try
            {
                var viewModel = _appService.GetAll();
                return View(viewModel);
            }
            catch (Exception ex)
            {
                return ErrorMessage(_logger, ex);
            }
        }

        [Authorize]
        public IActionResult Detail(int? taskId)
        {
            try
            {
                if ((taskId != null) && (taskId > 0))
                    return View(_appService.GetById((int)taskId));
                else
                    return View(new TaskDetailViewModel());
            }
            catch (Exception ex)
            {
                return ErrorMessage(_logger, ex);
            }
        }

        [Authorize]
        [HttpPost]
        public IActionResult Save(TaskInputModel inputModel)
        {
            try
            {
                var viewModel = _appService.Save(inputModel);
                return SuccessMessage("Salvo com sucesso!", viewModel.Task.Id, false);
            }
            catch (Exception ex)
            {
                return ErrorMessage(_logger, ex);
            }
        }

        [Authorize]
        [HttpDelete]
        public IActionResult Remove(int taskId)
        {
            try
            {
                _appService.DeleteById(taskId);
                return SuccessMessage("Excluído com sucesso!", null, true);
            }
            catch (Exception ex)
            {
                return ErrorMessage(_logger, ex);
            }
        }
    }
}

Project/Backend_.NetCore_3_1/StefaniniCore.UI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc;
@using System.Security.Claims;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StefaniniCore.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/my-css/my-styles.css" rel="stylesheet" />
    <script src="~/js/my-scripts/common/generic.js"></script>
</head>
<body>

    @{
        async Task RenderMenu(bool hasClaims)
        {
            <header>
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                    <div class="container">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                                <ul class="navbar-nav flex-grow-1">
                                    <li class="nav-item">@Html.ActionLink("Funcionalidades", "List", "Tasks", null, new { @class = "nav-link" })</li>
                                    <li class="nav-item">@Html.ActionLink("Novo Usuário", "Detail", "UserSystems", null, new { @class = "nav-link" })</li>
                                    <li class="nav-item">@Html.ActionLink("Perfis", "List", "ProfileTypes", null, new { @class = "nav-link" })</li>
                                    @if (!hasClaims)
                                    {
                                        <li class="nav-item">@Html.ActionLink("SignIn", "SignIn", "UserSystems", null, new { @class = "nav-link" })</li>
                                    }
                                    <li class="nav-item">@Html.ActionLink("SignOut", "SignOut", "UserSystems", null, new { @class = "nav-link" })</li>
                                </ul>
                        </div>
                    </div>
                </nav>
            </header>
        }

        bool hasClaims = (User.FindFirst(ClaimTypes.Name)?.Value) != null ? true : false;

        if (hasClaims)
        {
            await RenderMenu(hasClaims);
        }
        else
        {
            <header class="headerNoSignIn">
            </header>
        }
    }


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - StefaniniCore.UI</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>